"""Generate perspective models from perspective/contracts.py.

This mini generator keeps the shared perspective package independent from any
single domain while reusing the same generation helpers as sync_domain.py.

Usage:
    python perspective/gen_models.py
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from tools.contracts import GenerationContract  # noqa: E402
from tools.scripts.sync_domain import (         # noqa: E402
    generate_empty_constants,
    generate_generation_model,
    parse_generation_contract,
)

PACKAGE = Path(__file__).resolve().parent

ZONE_START = (
    "# -- Model generation zone: generated by perspective/gen_models.py, "
    "do not edit --"
)
ZONE_END = "# -- Model generation zone end --"


def _load_module(path: Path):
    """Load a Python file directly and avoid package import side effects."""
    mod_name = f"_perspective_{path.stem}"
    spec = importlib.util.spec_from_file_location(mod_name, path)
    if spec is None or spec.loader is None:
        raise SystemExit(f"Cannot load module: {path}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[mod_name] = mod
    spec.loader.exec_module(mod)
    return mod


def _find_contract(mod):
    """Find the single GenerationContract subclass in the loaded module."""
    for attr_name in dir(mod):
        obj = getattr(mod, attr_name)
        if (
            isinstance(obj, type)
            and issubclass(obj, GenerationContract)
            and obj is not GenerationContract
        ):
            return obj
    raise SystemExit("perspective/contracts.py has no GenerationContract subclass")


def _gen_zone_code(cls: type) -> str:
    """Generate model code and an EMPTY_* constant from a contract class."""
    model_cls = cls.__name__.removesuffix("GenerationContract")
    fields = parse_generation_contract(cls)
    model_code = generate_generation_model(model_cls, fields)
    empty_code = generate_empty_constants(model_cls, fields).replace(
        "_EMPTY_", "EMPTY_"
    )
    return model_code + "\n\n\n" + empty_code


def main() -> None:
    contracts_path = PACKAGE / "contracts.py"
    if not contracts_path.exists():
        raise SystemExit(f"{contracts_path} does not exist")
    cls = _find_contract(_load_module(contracts_path))
    code = _gen_zone_code(cls)

    models_path = PACKAGE / "models.py"
    raw = models_path.read_text(encoding="utf-8")
    if ZONE_START not in raw or ZONE_END not in raw:
        raise SystemExit(
            f"{models_path.name} is missing the model generation zone:\n"
            f"{ZONE_START}\n{ZONE_END}"
        )

    nl = "\r\n" if "\r\n" in raw else "\n"
    code_block = nl.join(code.split("\n"))
    block = ZONE_START + nl + nl + code_block + nl + nl + nl + ZONE_END
    start_idx = raw.index(ZONE_START)
    end_idx = raw.index(ZONE_END) + len(ZONE_END)
    models_path.write_text(raw[:start_idx] + block + raw[end_idx:], encoding="utf-8")
    print("SUCCESS!")


if __name__ == "__main__":
    main()
